const $ = (s) => document.querySelector(s);
const STORE = { done:'csp_done', notes:'csp_notes', code:'csp_code', quiz:'csp_quiz', settings:'csp_settings' };
const load = (k, f={}) => { try { return JSON.parse(localStorage.getItem(k) || JSON.stringify(f)); } catch { return f; } };
const save = (k, v) => localStorage.setItem(k, JSON.stringify(v));
let done = load(STORE.done), notes = load(STORE.notes), codeStore = load(STORE.code), quizStore = load(STORE.quiz);
let settings = Object.assign({theme:'dark', last:null}, load(STORE.settings));
let state = { view:'home', course:null, lesson:null, filter:'all', search:'' };
const courses = () => DATA.courses;
const lessonsOf = (c) => c.modules.flatMap(m => m.lessons.map(l => ({...l, module:m.title, courseId:c.id, courseName:c.name, icon:c.icon})));
const allLessons = () => courses().flatMap(lessonsOf);
const courseBy = (id) => courses().find(c => c.id === id) || courses()[0];
const pct = (a,b) => b ? Math.round(a/b*100) : 0;
const esc = (s='') => String(s).replace(/[&<>'"]/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
const countDone = () => allLessons().filter(l => done[l.id]).length;
function init(){ document.body.classList.toggle('light', settings.theme==='light'); readHash(); render(); if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js').catch(()=>{}); }
function readHash(){ const h = location.hash.slice(1).split('/'); if(h[0]) state.view=h[0]; if(h[1]) state.course=h[1]; if(h[2]) state.lesson=h[2]; }
function route(view, course=state.course, lesson=state.lesson){ state.view=view; state.course=course; state.lesson=lesson; location.hash = [view,course,lesson].filter(Boolean).join('/'); render(); setTimeout(()=>scrollTo(0,0),0); }
function openCourse(id){ const c=courseBy(id); const first=lessonsOf(c).find(l=>!done[l.id]) || lessonsOf(c)[0]; route('course', id, first.id); }
function currentLesson(){ const c=courseBy(state.course); return lessonsOf(c).find(l=>l.id===state.lesson) || lessonsOf(c)[0]; }
function setTheme(){ settings.theme = settings.theme==='light'?'dark':'light'; save(STORE.settings, settings); document.body.classList.toggle('light', settings.theme==='light'); }
function toast(msg){ const t=$('.toast'); if(!t) return; t.textContent=msg; t.classList.add('show'); setTimeout(()=>t.classList.remove('show'),2200); }
function render(){ const app=$('#app'); app.className='app'; app.innerHTML = `${top()}<main class="main">${body()}</main>${bottom()}<div class="toast"></div>`; }
function top(){ const total=allLessons().length, d=countDone(); return `<header class="top"><div class="brand"><div class="brand-left"><div class="logo">CS</div><div><h1>CodeStudy Pro</h1><small>${d}/${total} aulas concluídas • ${pct(d,total)}%</small></div></div><button class="round" onclick="setTheme()">Tema</button></div></header>`; }
function bottom(){ const items=[['home','Cursos'],['plan','Plano'],['quiz','Prova'],['challenges','Desafios'],['profile','Perfil']]; return `<nav class="bottom-nav">${items.map(([v,t])=>`<button class="${state.view===v?'active':''}" onclick="route('${v}')">${t}</button>`).join('')}</nav>`; }
function body(){ if(state.view==='course') return courseView(); if(state.view==='plan') return planView(); if(state.view==='quiz') return quizView(); if(state.view==='challenges') return challengesView(); if(state.view==='profile') return profileView(); if(state.view==='search') return searchView(); return homeView(); }
function homeView(){ const total=allLessons().length, d=countDone(); const last=settings.last ? allLessons().find(l=>l.id===settings.last) : null; const next=allLessons().find(l=>!done[l.id]) || allLessons()[0]; return `<section class="hero card"><span class="badge">Feito para celular e APK</span><h2>Aprenda programando, não só lendo.</h2><p>Aulas curtas, explicação real, exemplo comentado, prática com correção básica e prova para fixar.</p><div class="stats"><div class="stat"><strong>${pct(d,total)}%</strong><span>progresso</span></div><div class="stat"><strong>${d}</strong><span>aulas feitas</span></div><div class="stat"><strong>${total-d}</strong><span>faltam</span></div></div><div class="quick"><button class="quick-card" onclick="${last?`route('course','${last.courseId}','${last.id}')`:`openCourse('${next.courseId}')`}"><b>Continuar</b><span>${last?esc(last.courseName+' • '+last.title):'Começar agora'}</span></button><button class="quick-card" onclick="route('search')"><b>Buscar aula</b><span>Encontre HTML, CSS, JS, Java...</span></button></div></section><div class="section-title"><h2>Cursos</h2><span>ordem recomendada</span></div><section class="grid">${courses().map(courseCard).join('')}</section>`; }
function courseCard(c){ const list=lessonsOf(c), d=list.filter(l=>done[l.id]).length, p=pct(d,list.length); return `<article class="card course-card" onclick="openCourse('${c.id}')"><div class="course-top"><div class="course-icon">${c.icon}</div><span class="badge">${p}%</span></div><h3>${esc(c.name)}</h3><p>${esc(c.desc)}</p><div class="progress"><span style="width:${p}%"></span></div><small>${d}/${list.length} aulas</small><br><br><button class="btn primary full">Estudar</button></article>`; }
function courseView(){ const c=courseBy(state.course), lesson=currentLesson(); settings.last=lesson.id; save(STORE.settings, settings); const list=lessonsOf(c), i=list.findIndex(l=>l.id===lesson.id); return `<section class="course-layout"><aside class="desktop-sticky"><div class="lesson-top"><button class="btn" onclick="route('home')">Voltar</button><div><b>${c.icon} ${esc(c.name)}</b><br><small class="muted">Aula ${i+1}/${list.length}</small></div></div><details class="card" open><summary>Lista de aulas</summary><div class="inside lesson-list">${list.map(l=>`<button class="lesson-btn ${l.id===lesson.id?'active':''} ${done[l.id]?'done':''}" onclick="route('course','${c.id}','${l.id}')">${done[l.id]?'✓ ':''}${esc(l.title)}</button>`).join('')}</div></details></aside><article class="lesson card">${lessonHtml(lesson,c,i,list)}</article></section>`; }
function lessonHtml(l,c,i,list){ const prev=list[Math.max(0,i-1)], next=list[Math.min(list.length-1,i+1)]; return `<div class="lesson-head"><span class="badge">${esc(l.level)} • ${l.minutes} min</span><span class="badge">${esc(l.module)}</span></div><h2>${esc(l.title)}</h2><div class="progress"><span style="width:${pct(i+1,list.length)}%"></span></div><h3>Objetivo da aula</h3><div class="learn-card"><strong>O que você precisa sair sabendo</strong><p>${esc(l.objective)}</p></div><h3>Explicação de verdade</h3>${l.explain.map(p=>`<p>${esc(p)}</p>`).join('')}<div class="learn-card"><strong>Modelo mental</strong><p>${esc(l.mental)}</p></div><h3>Passo a passo</h3><div class="steps">${l.steps.map(s=>`<div class="step">${esc(s)}</div>`).join('')}</div><h3>Exemplo prático</h3><pre class="code">${esc(l.code)}</pre><h3>O que cada parte faz</h3><div class="line-table">${l.lines.map(([a,b])=>`<div class="line"><b>${esc(a)}</b><span>${esc(b)}</span></div>`).join('')}</div><h3>Checklist de domínio</h3><ul>${l.checkpoints.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h3>Erros comuns</h3><ul>${l.mistakes.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${labHtml(l)}${quizOneHtml(l)}<h3>Anotação rápida</h3><textarea class="note" oninput="saveNote('${l.id}',this.value)" placeholder="Resuma com suas palavras. Não copie a explicação.">${esc(notes[l.id]||'')}</textarea><div class="quick-row" style="margin-top:12px"><button class="btn" onclick="route('course','${c.id}','${prev.id}')">Anterior</button><button class="btn" onclick="route('course','${c.id}','${next.id}')">Próxima</button></div><button class="btn primary full" style="margin-top:10px" onclick="finishLesson('${l.id}')">Marcar como concluída</button>`; }
function labHtml(l){ const val=codeStore[l.id] || l.starter || ''; return `<h3>Prática guiada</h3><div class="lab"><p>${esc(l.practice)}</p><textarea id="code-${l.id}" spellcheck="false">${esc(val)}</textarea><button class="btn primary full" style="margin-top:10px" onclick="checkLab('${l.id}')">Corrigir prática</button><div id="fb-${l.id}"></div></div>`; }
function quizOneHtml(l){ const q=l.quiz, saved=quizStore[l.id]; return `<h3>Teste rápido</h3><div class="learn-card"><strong>${esc(q.q)}</strong>${q.options.map((o,idx)=>`<label class="option"><input type="radio" name="q-${l.id}" value="${idx}" ${saved==idx?'checked':''}>${esc(o)}</label>`).join('')}<button class="btn" onclick="answerQuiz('${l.id}')">Responder</button><div id="quizfb-${l.id}">${saved!==undefined?quizFeedback(l,saved):''}</div></div>`; }
function quizFeedback(l,idx){ const ok=Number(idx)===l.quiz.answer; return `<div class="feedback ${ok?'good':'bad'}"><b>${ok?'Acertou':'Errou'}</b><p>${esc(l.quiz.why)}</p></div>`; }
function saveNote(id,v){ notes[id]=v; save(STORE.notes, notes); }
function finishLesson(id){ done[id]=true; save(STORE.done, done); toast('Aula concluída. Bom. Agora faça a próxima prática.'); render(); }
function checkLab(id){ const l=allLessons().find(x=>x.id===id), txt=$(`#code-${id}`).value; codeStore[id]=txt; save(STORE.code, codeStore); const miss=(l.validator?.must||[]).filter(m=>!txt.toLowerCase().includes(m.toLowerCase())); const fb=$(`#fb-${id}`); if(!miss.length){ fb.innerHTML=`<div class="feedback good"><b>Boa prática.</b><p>Seu código contém os pontos principais. Agora explique em voz alta o que cada parte faz.</p></div>`; } else { fb.innerHTML=`<div class="feedback bad"><b>Faltam ${miss.length} ponto(s):</b><p>${miss.map(esc).join(', ')}</p><p>${esc(l.validator.tip)}</p></div>`; } }
function answerQuiz(id){ const l=allLessons().find(x=>x.id===id), el=document.querySelector(`input[name="q-${id}"]:checked`); if(!el){toast('Escolha uma resposta.'); return;} quizStore[id]=Number(el.value); save(STORE.quiz, quizStore); $(`#quizfb-${id}`).innerHTML=quizFeedback(l,Number(el.value)); }
function planView(){ return `<section class="card"><span class="badge">Plano rápido</span><h2>Rotina para aprender sem se perder</h2><p>Faça pouco, mas faça direito: aula, prática, correção e revisão.</p></section><div class="section-title"><h2>Semana recomendada</h2><span>30 a 60 min/dia</span></div><section class="grid">${DATA.plan.map(p=>`<article class="card"><span class="badge">${esc(p.day)}</span><h3>${esc(p.focus)}</h3><p>${esc(p.task)}</p></article>`).join('')}</section>`; }
function quizView(){ const qs=allLessons().map(l=>({...l, q:l.quiz})); return `<section class="card"><span class="badge">Prova geral</span><h2>Teste se você entendeu</h2><p>Responda sem olhar a aula. Se errar, volte na explicação e refaça a prática.</p></section><section>${qs.map(l=>`<div class="card" style="margin-top:12px"><b>${esc(l.courseName)} • ${esc(l.title)}</b>${quizOneHtml(l)}</div>`).join('')}</section>`; }
function challengesView(){ const filters=[['all','Todos'],...courses().map(c=>[c.id,c.name])]; const list=DATA.challenges.filter(c=>state.filter==='all'||c.course===state.filter); return `<section class="card"><span class="badge">Projetos pequenos</span><h2>Desafios para aprender de verdade</h2><p>Escolha um desafio, faça no editor e use os critérios para corrigir.</p><div class="pill-row">${filters.map(([id,t])=>`<button class="pill ${state.filter===id?'active':''}" onclick="state.filter='${id}';render()">${esc(t)}</button>`).join('')}</div></section><section class="grid" style="margin-top:12px">${list.map(c=>`<article class="card challenge"><span class="badge">${esc(c.level)}</span><h3>${esc(c.title)}</h3><p>${esc(c.brief)}</p><b>Requisitos</b><ul>${c.requirements.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><b>Critérios</b><ul>${c.rubric.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></article>`).join('')}</section>`; }
function profileView(){ const total=allLessons().length,d=countDone(); return `<section class="card"><span class="badge">Perfil local</span><h2>Seu progresso</h2><div class="stats"><div class="stat"><strong>${d}</strong><span>feitas</span></div><div class="stat"><strong>${total-d}</strong><span>faltam</span></div><div class="stat"><strong>${pct(d,total)}%</strong><span>total</span></div></div><br><button class="btn" onclick="exportData()">Exportar backup</button> <button class="btn" onclick="resetProgress()">Zerar progresso</button></section><div class="section-title"><h2>Por curso</h2></div><section class="grid">${courses().map(courseCard).join('')}</section>`; }
function searchView(){ const q=state.search.toLowerCase(); const list=allLessons().filter(l=>(l.title+l.courseName+l.objective).toLowerCase().includes(q)); return `<section class="card"><h2>Buscar aula</h2><input class="search" placeholder="Ex: função, CSS, Java, backend" value="${esc(state.search)}" oninput="state.search=this.value;render()"></section><section style="margin-top:12px" class="lesson-list">${list.map(l=>`<button class="lesson-btn" onclick="route('course','${l.courseId}','${l.id}')"><b>${esc(l.courseName)}</b><br>${esc(l.title)}</button>`).join('')}</section>`; }
function exportData(){ const blob=new Blob([JSON.stringify({done,notes,codeStore,quizStore},null,2)],{type:'application/json'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='codestudy-backup.json'; a.click(); }
function resetProgress(){ if(confirm('Zerar progresso deste aparelho?')){ localStorage.clear(); location.reload(); } }
window.addEventListener('hashchange',()=>{readHash(); render();});
init();
